package parallel.runners;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)
@CucumberOptions(
    monochrome = false,
    features = {"classpath:parallel/features/api_scenario001_run001_IT.feature"},
    glue = "steps",
    format = {"json:target/cucumber-report/api_scenario001_run001_IT.json"}
)
public class api_scenario001_run001_IT {
}
// Generated by Cucable

