Feature: API functionality

Scenario: GET testing

When User sends GET request to endpoint http://services.groupkt.com/country/get/iso3code/USA
Then User receives response with the following data
|responseCode|name|alpha2_code|alpha3_code|messages|
|200|United States of America|US|USA|Country found matching code [USA].|

# Generated by Cucable

