Feature: Login/Log out functionality

Scenario: Login with invalid credentials

Given User opens Home page
When User signs in with login 123qwer.com and password lucky125
Then Error message Please enter a valid email address. appears

# Generated by Cucable

