Feature: Login functionality

Scenario: Login with invalid credentials

Given User opens Home page
When User signs in with login  and password lucky125
Then Error message Email address is required. appears

# Generated by Cucable

