Feature: Search functionality

Scenario: Search results contain keyword

Given User is logged in and opens HomePage
When User submit search query Canon
Then All search results contain keyword

# Generated by Cucable

